POST http://localhost:3000/api/rounds/821b53f3-7a7d-4e59-8b76-b2c80cc38d1c/claim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZGVsdmV5IiwiYmFsYW5jZSI6MCwiaWF0IjoxNzU3MjAxOTczfQ.0xg8yDTVg0wD4opZsQzMLmEWOEkSIzeUFEUAZgxmhbw

{ }